# Generated by Django 6.0.5 on 2026-06-04 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='letters/pdfs/')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='letters/signed/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='letters.letter')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signing_order'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('date', 'Date'), ('text', 'Text'), ('initial', 'Initials')], max_length=20)),
                ('page_number', models.IntegerField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('width', models.FloatField(default=150)),
                ('height', models.FloatField(default=50)),
                ('value', models.TextField(blank=True, null=True)),
                ('stamp_text', models.CharField(blank=True, max_length=255, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='letters.signaturerequest')),
            ],
        ),
    ]
