# Generated by Django 6.0.5 on 2026-06-12 18:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('requires_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('security_clearance_level', models.SmallIntegerField(default=1)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_updated_at', models.DateTimeField(auto_now_add=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='archive_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='archive_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('mfa_verified', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('access_policy', models.SmallIntegerField(choices=[(1, 'Private'), (2, 'Department'), (3, 'Authenticated Users'), (4, 'Public')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_department', models.CharField(blank=True, help_text='Department that can view this collection (if access_policy = Department)', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('loan', 'Loan Document'), ('department', 'Department Document'), ('public', 'Public Document')], default='loan', max_length=20)),
                ('client_name', models.CharField(blank=True, db_index=True, help_text='Name of the customer/borrower (only for loan documents)', max_length=200, null=True)),
                ('customer_id', models.CharField(blank=True, db_index=True, help_text='Unique customer identifier (only for loan documents)', max_length=50, null=True)),
                ('loan_id', models.CharField(blank=True, db_index=True, help_text='Unique loan identifier (only for loan documents)', max_length=50, null=True)),
                ('period', models.CharField(blank=True, help_text="e.g., 'Annual Review 2024', 'Q1 2025'", max_length=100)),
                ('product_type', models.CharField(blank=True, help_text='Type of loan (e.g., Mortgage, Personal, Business)', max_length=100)),
                ('date_of_disbursement', models.DateField(blank=True, help_text='Date the loan was disbursed', null=True)),
                ('loan_status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], db_index=True, default='active', help_text='Current status of the loan', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('encryption_key_id', models.CharField(blank=True, help_text='Reference to HSM/KMS key', max_length=100)),
                ('integrity_hash', models.CharField(blank=True, help_text='SHA‑256 of all file hashes', max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_items', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='archive.collection')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='archive.tag')),
            ],
            options={
                'permissions': [('can_approve_items', 'Can approve archive items for publishing'), ('can_view_sensitive_metadata', 'Can view encrypted/restricted metadata'), ('can_change_loan_status', 'Can update the loan status (active/closed/defaulted)')],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_folders', to='archive.archiveitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='archive.documentfolder')),
            ],
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(help_text='Path in secure object storage', max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('hash_sha256', models.CharField(db_index=True, help_text='SHA‑256 for integrity', max_length=64)),
                ('encrypted', models.BooleanField(default=True)),
                ('thumbnail_s3_key', models.CharField(blank=True, help_text='Pre‑generated thumbnail', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('virus_scan_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Clean'), (2, 'Infected')], default=0)),
                ('virus_scan_at', models.DateTimeField(blank=True, null=True)),
                ('archive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='archive.archiveitem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archive.foldertype')),
            ],
            options={
                'ordering': ['parent__id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stored_path', models.CharField(blank=True, help_text='Storage path relative to MEDIA_ROOT', max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('item_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_text', to='archive.itemfile')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signature_type', models.CharField(choices=[('simple', 'Simple/Visible'), ('certificate', 'Digital Certificate')], default='simple', max_length=20)),
                ('page_number', models.IntegerField(default=0)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('signature_width', models.FloatField(default=200)),
                ('signature_height', models.FloatField(default=80)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('certificate_signer_name', models.CharField(blank=True, max_length=200)),
                ('certificate_serial_number', models.CharField(blank=True, max_length=100)),
                ('certificate_issuer', models.CharField(blank=True, max_length=200)),
                ('signing_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for signing', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Location where signed', max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='signed_documents/')),
                ('signed_file_hash', models.CharField(blank=True, help_text='SHA-256 of signed file', max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_signatures', to=settings.AUTH_USER_MODEL)),
                ('document_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='archive.documentfile')),
                ('item_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='archive.itemfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text='Custom name for subfolders (if folder_type is null)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='archive.archiveitem')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('folder_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.foldertype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archive.itemfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parent__id', 'folder_type__order'],
            },
        ),
        migrations.AddField(
            model_name='itemfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='archive.itemfolder'),
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletions', to=settings.AUTH_USER_MODEL)),
                ('item_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='archive.itemfile')),
                ('item_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='archive.itemfolder')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('field_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('json', 'JSON'), ('encrypted', 'Encrypted')], default='string', max_length=20)),
                ('archive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metadata', to='archive.archiveitem')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('guarantees', 'Guarantees'), ('collateral_of', 'Collateral Of'), ('amendment_to', 'Amendment To'), ('parent_loan', 'Parent Loan'), ('sub_loan', 'Sub Loan'), ('cross_default', 'Cross Default'), ('associated', 'Associated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='archive.archiveitem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='archive.archiveitem')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folders', to=settings.AUTH_USER_MODEL)),
                ('doc_files', models.ManyToManyField(blank=True, related_name='shared_folders', to='archive.documentfile')),
                ('loan_files', models.ManyToManyField(blank=True, related_name='shared_folders', to='archive.itemfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedFolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('shared_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_users', to='archive.sharedfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folders_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFolderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_in', to='archive.itemfile')),
                ('shared_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='archive.sharedfolder')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, help_text='Message to signers')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('signing_order', models.CharField(choices=[('parallel', 'Parallel'), ('sequential', 'Sequential')], default='parallel', max_length=20)),
                ('reminder_days', models.IntegerField(default=3, help_text='Days between reminders')),
                ('expires_days', models.IntegerField(default=30, help_text='Days until envelope expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='signed_envelopes/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_envelopes', to=settings.AUTH_USER_MODEL)),
                ('document_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='archive.documentfile')),
                ('item_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='archive.itemfile')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('signer', 'Needs to Sign'), ('approver', 'Needs to Approve'), ('cc', 'Receives Copy')], default='signer', max_length=20)),
                ('signing_order', models.IntegerField(default=0, help_text='Order in which this recipient signs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signing_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('saved_signature', models.TextField(blank=True, null=True)),
                ('saved_signature_path', models.CharField(blank=True, max_length=500, null=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='archive.signatureenvelope')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signing_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initial', 'Initials'), ('date', 'Date Signed'), ('text', 'Text Field'), ('checkbox', 'Checkbox')], default='signature', max_length=20)),
                ('label', models.CharField(blank=True, help_text="Field label (e.g., 'Sign Here')", max_length=100)),
                ('page_number', models.IntegerField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('width', models.FloatField(default=150)),
                ('height', models.FloatField(default=50)),
                ('required', models.BooleanField(default=True)),
                ('signed_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='archive.signatureenvelope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='archive.signaturerecipient')),
            ],
            options={
                'ordering': ['page_number', 'y_position', 'x_position'],
            },
        ),
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='archive.userfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='user_folders',
            field=models.ManyToManyField(blank=True, related_name='items', to='archive.userfolder'),
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='archive.workflowstatus'),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('granted_access_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('archive_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='archive.archiveitem')),
            ],
            options={
                'indexes': [models.Index(fields=['requester_user', 'status'], name='archive_acc_request_3e6c10_idx'), models.Index(fields=['archive_item', 'status'], name='archive_acc_archive_a98a66_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('VIEW', 'View'), ('MODIFY', 'Modify'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('CHANGE_PERMISSION', 'Change Permission')], max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='archive.archiveitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='archive_aud_user_id_3c1126_idx'), models.Index(fields=['archive_item', 'timestamp'], name='archive_aud_archive_a3c2e8_idx'), models.Index(fields=['action'], name='archive_aud_action_c076ca_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['access_policy'], name='archive_col_access__6d1f41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfolder',
            unique_together={('archive_item', 'user', 'name')},
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['archive_item', 'virus_scan_status'], name='archive_fil_archive_acaf60_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['hash_sha256'], name='archive_fil_hash_sh_53e6d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foldertype',
            unique_together={('parent', 'order')},
        ),
        migrations.AddIndex(
            model_name='digitalsignature',
            index=models.Index(fields=['signed_by', 'created_at'], name='archive_dig_signed__3378b0_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalsignature',
            index=models.Index(fields=['item_file', 'is_valid'], name='archive_dig_item_fi_9fe812_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalsignature',
            index=models.Index(fields=['document_file', 'is_valid'], name='archive_dig_documen_682baf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemfolder',
            unique_together={('archive_item', 'user', 'folder_type')},
        ),
        migrations.AddIndex(
            model_name='deletionrequest',
            index=models.Index(fields=['status', 'requested_at'], name='archive_del_status_95cc94_idx'),
        ),
        migrations.AddIndex(
            model_name='metadatafield',
            index=models.Index(fields=['field_name'], name='archive_met_field_n_aef918_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metadatafield',
            unique_together={('archive_item', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='relateditem',
            index=models.Index(fields=['from_item', 'relation_type'], name='archive_rel_from_it_0a91fe_idx'),
        ),
        migrations.AddIndex(
            model_name='relateditem',
            index=models.Index(fields=['to_item', 'relation_type'], name='archive_rel_to_item_0cc645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relateditem',
            unique_together={('from_item', 'to_item', 'relation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sharedfolderaccess',
            unique_together={('shared_folder', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='sharedfolderfile',
            unique_together={('shared_folder', 'item_file')},
        ),
        migrations.AddIndex(
            model_name='signatureenvelope',
            index=models.Index(fields=['status', 'created_at'], name='archive_sig_status_fd4e76_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureenvelope',
            index=models.Index(fields=['created_by', 'status'], name='archive_sig_created_7e1b64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfolder',
            unique_together={('user', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['collection', 'status'], name='archive_arc_collect_e6bb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['status', 'retention_until'], name='archive_arc_status__a9519b_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='archive_arc_is_dele_2d7214_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['client_name'], name='archive_arc_client__dd4eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['customer_id'], name='archive_arc_custome_d37d09_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['loan_id'], name='archive_arc_loan_id_3122e8_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['loan_status'], name='archive_arc_loan_st_dfba6b_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['document_type'], name='archive_arc_documen_79ad36_idx'),
        ),
    ]
